app/regiohelden/bank_users/urls.py
from django.conf.urls import url
from django.contrib import admin
from bank_users.views import *
from django.conf.urls import include


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^add/',createBankingUser,name='addUser'),
    url(r'^delete/',deleteBankingUser,name='deleteUser'),
    url(r'^update/',updateBankingUser,name='updateUser'),
    url(r'^view/',readBankingUser,name='viewUser'),
    url(r'^login/',login,name='login'),
    url(r'^logout/',logout,name='logout'),
]

app/regiohelden/regiohelden/urls.py
from django.conf.urls import url
from django.contrib import admin
from bank_users.views import *
from django.conf.urls import include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'', include('bank_users.urls', namespace='bank_users')),
]

app/regiohelden/templates/base.html
{% load staticfiles %}

<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	{% block script %} {% endblock %}
</head>
<body>
	{% block main %}{% endblock %}
</body>

app/regiohelden/templates/createUser.html
{% if not created %}
	<h3>Bank user creation failed.</h3>
{% endif %}

<div><a href="{% url 'bank_users:home' %}">Home</a></div><br>

<div>
	<form action="{% url 'bank_users:addUser' %}" method="post">
	    {% csrf_token %}
	    {{ iban }}
	    {{ userform }}
	    <input type="submit" value="Submit" />
	</form>
</div>

app/regiohelden/templates/deleteUser.html
{% extends 'base.html' %}

{% block main %}
	<a href="{% url 'bank_users:home' %}">Home</a><br><br>

	{% if not_deleted %}
		Wrong combination of first name and last name.<br><br>
	{% endif %}

		<form action="{% url 'bank_users:deleteUser' %}" method="post">
		    {% csrf_token %}
		    {{ form }}
		    <input type="submit" value="Submit" />
	    </form>

{% endblock %}

app/regiohelden/templates/home.html
<div><a>Hello {{ user.get_full_name|default:user.username }}!</a></div>
<div><a href="{% url 'bank_users:logout' %}">Logout</a></div><br>

{% if created %}
	<h3>Bank user created.</h3><br>
{% endif %}

{% if updated %}
	<h3>Bank user updated.</h3><br>
{% endif %}

{% if deleted %}
	<h3>Bank user deleted.</h3><br>
{% endif %}

<div><a href="{% url 'bank_users:addUser' %}">Add user</a></div><br>
<div><a href="{% url 'bank_users:viewUser' %}">View user</a></div><br>
<div><a href="{% url 'bank_users:updateUser' %}">Update user</a></div><br>
<div><a href="{% url 'bank_users:deleteUser' %}">Delete user</a></div>

app/regiohelden/templates/login.html
<a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a>

app/regiohelden/templates/readUser.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block script %}
	<script src="{% static 'js/readUser.js' %}"></script>
	<script>var url = "{% url 'bank_users:viewUser' %}";</script>

{% endblock %}

{% block main %}
	<a href="{% url 'bank_users:home' %}">Home</a>
	<div id="getdetails">  
	    {% csrf_token %}
	    {{ form }}
	    <input type="submit" id="submit" value="Submit" />
	</div>
	<div id="showdetails"> 
	</div>
{% endblock %}

app/regiohelden/templates/updateUser.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block script %}<script src="{% static 'js/updateUser.js' %}"></script>{% endblock %}

{% block main %}
	<a href="{% url 'bank_users:home' %}">Home</a><br><br>
	
	{% if not_updated %}
		Wrong combination of first name and last name<br><br>
	{% endif %}

	{% if userdetails %}
		<script>
			var first_name = "{{ userdetails.first_name}}";
			var last_name = "{{ userdetails.last_name }}";
			var countrycode = "{{ iban.countrycode }}";
			var swiftcode = "{{ iban.swiftcode }}";
			var accountnumber = "{{ iban.accountnumber }}";
			var checksum = "{{ iban.checksum }}";
		</script>
		<div id="block">
			<form action="{% url 'bank_users:updateUser' %}" method="post">
				{% csrf_token %}
				{{ form }}
				<input type="hidden" name="old_first_name" value="{{ userdetails.first_name }}">
				<input type="hidden" name="old_last_name" value="{{ userdetails.last_name }}">
				<input type="submit" id="submit" value="Submit" />
			</form>
		</div>
	{% else %}

		<form action="{% url 'bank_users:updateUser' %}" method="get">
		    {% csrf_token %}
		    {{ form }}
		    <input type="submit" value="Submit" />
	    </form>

    {% endif %}

{% endblock %}